version: "3.9"
services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase-production
    hostname: metabase
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabaseappdb
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: Muhammadyk1$
      MB_DB_HOST: postgres
    ports:
      - 8000:8000
    volumes:
      - metabase-data:/metabase-data
    networks:
      - metanet1
    restart: unless-stopped
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:15
    container_name: postgres-production
    hostname: postgres
    environment:
      POSTGRES_USER: metabase
      POSTGRES_DB: metabaseappdb
      POSTGRES_PASSWORD: Muhammadyk1
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - metanet1
    restart: unless-stopped

volumes:
  postgres-data:
  metabase-data:

networks:
  metanet1:
    driver: bridge
